
    create table tb_mtt_estacao (
        dt_criacao date not null,
        dt_ultima_atualizacao date,
        nr_capacidade number(10,0),
        id_estacao number(19,0) generated by default as identity,
        ds_status varchar2(30 char) not null,
        ds_responsavel varchar2(100 char),
        nm_estacao varchar2(100 char) not null unique,
        ds_localizacao varchar2(200 char),
        primary key (id_estacao)
    );

    create table tb_mtt_historico_moto (
        dt_acao date not null,
        id_historico number(19,0) generated by default as identity,
        id_moto number(19,0) not null,
        id_usuario number(19,0) not null,
        tp_acao varchar2(20 char) not null,
        primary key (id_historico)
    );

    create table tb_mtt_moto (
        nr_ano number(10,0),
        id_estacao number(19,0) not null,
        id_moto number(19,0) generated by default as identity,
        ds_placa varchar2(10 char) not null unique,
        ds_vaga varchar2(10 char) unique,
        ds_cor varchar2(30 char),
        ds_status varchar2(50 char),
        nm_modelo varchar2(100 char) not null,
        primary key (id_moto)
    );

    create table tb_mtt_usuario (
        id_usuario number(19,0) generated by default as identity,
        tp_usuario varchar2(50 char) not null,
        ds_email varchar2(100 char) not null unique,
        ds_senha varchar2(100 char) not null,
        nm_usuario varchar2(100 char) not null,
        primary key (id_usuario)
    );

    alter table tb_mtt_historico_moto 
       add constraint FKdkfv3ox9x42k7cib120gbm3km 
       foreign key (id_moto) 
       references tb_mtt_moto;

    alter table tb_mtt_historico_moto 
       add constraint FKcqsscnqhd160dax878fp7jdbn 
       foreign key (id_usuario) 
       references tb_mtt_usuario;

    alter table tb_mtt_moto 
       add constraint FK7vsh8oolos7nfuvy22ydgxqsa 
       foreign key (id_estacao) 
       references tb_mtt_estacao;
